kelime = ["elma", "araba", "okul", "kitap", "masa", "kalem", "kedi", "köpek", "su", "ayakkabı",
    "güneş", "deniz", "ağaç", "çiçek", "yıldız", "dağ", "nehir", "göl", "hava", "rüzgar",
    "hayvan", "insan", "şehir", "ev", "baba", "anne", "çocuk", "dost", "arkadaş", "sandalye",
    "sofra", "çorba", "pizza", "hamburger", "tost", "salata", "şarkı", "müzik", "film", "televizyon",
    "bilgisayar", "telefon", "internet", "fotoğraf", "yazılım", "kütüphane", "oyun", "eğlence", "tarih", "coğrafya",
    "matematik", "fen", "kimya", "biyoloji", "fizik", "edebiyat", "resim", "mimarlık", "mühendislik", "tıp",
    "okuma", "yazma", "dinleme", "konuşma", "öğrenme", "anlama", "yazı", "kalem", "defter", "not",
    "soru", "cevap", "ödev", "sınıf", "ders", "öğrenci", "öğretmen", "sınav", "puan", "başarı",
    "hayal", "gerçek", "gül", "mutlu", "üzgün", "sevgi", "aşk", "nefret", "korku", "cesaret",
    "umut", "hayal", "mücadele", "özlem", "güç", "yetenek", "hobi", "spor", "sağlık", "beslenme",
    "uyku", "dinlenme", "yürüyüş", "koşu", "yüzme", "basketbol", "futbol", "tenis", "voleybol", "masa tenisi",
    "bisiklet", "kış", "yaz", "sonbahar", "ilkbahar", "mevsim", "hava durumu", "yağmur", "kar", "güneş",
    "bulut", "rüzgar", "fırtına", "sıcak", "soğuk", "sıcaklık", "soğukluk", "deniz", "okyanus", "dağ",
    "tepe", "vadi", "orman", "çöl", "nehir", "göl", "su", "toprak", "kaya", "kum",
    "bitki", "ağaç", "çalı", "çiçek", "meyve", "sebze", "tahıl", "hayvan", "kuş", "balık",
    "sürüngen", "memeli", "böcek", "yılan", "kaplumbağa", "tavuk", "koyun", "sığır", "at", "domuz",
    "kedi", "köpek", "fare", "maymun", "fil", "kaplan", "aslan", "zebra", "gergedan", "timsah",
    "yılan", "kertenkele", "salyangoz", "arı", "kelebek", "uçurtma", "balon", "kapı", "pencere", "duvar",
    "tavan", "yerde", "tavan", "odası", "salon", "banyo", "mutfak", "yatak", "çamaşır", "lavabo",
    "sabit", "değişken", "değer", "sayı", "string", "list", "tuple", "set", "dictionary", "fonksiyon",
    "method", "class", "nesne", "kütüphane", "modül", "paket", "betik", "işlem", "parametre",
    "değişken", "boolean", "int", "float", "string", "char", "kapsam", "döngü", "if", "else",
    "switch", "case", "while", "for", "do", "try", "catch", "finally", "exception", "hata",
    "debug", "sürücü", "yazıcı", "ekran", "klavye", "fare", "kamera", "mikrofon", "hoparlör", "monitör",
    "güç", "pil", "şarj", "elektrik", "devre", "yeni", "eski", "büyük", "küçük", "orta",
    "uzun", "kısa", "geniş", "dar", "açık", "kapalı", "temiz", "kirli", "yeni", "eski",
    "şık", "rahat", "sert", "yumuşak", "hafif", "ağır", "parlak", "soluk", "sade", "renkli",
    "dar", "geniş", "yüksek", "alçak", "koyu", "açık", "mavi", "yeşil", "kırmızı", "sarı",
    "turuncu", "mor", "pembe", "siyah", "beyaz", "kahverengi", "gri", "mavi", "siyah", "beyaz",
    "pembe", "mavi", "mavi", "yeşil", "kırmızı", "turuncu", "sarı", "mor", "siyah", "beyaz",
    "kırmızı", "yeşil", "mavi", "sarı", "mor", "pembe", "koyu", "açık", "farklı", "aynı",
    "sıralı", "karışık", "doğru", "yanlış", "hızlı", "yavaş", "kolay", "zor", "farklı", "benzer",
    "özel", "genel", "temel", "gelişmiş", "modern", "eski", "yeni", "sıfır", "iki", "üç",
    "dört", "beş", "altı", "yedi", "sekiz", "dokuz", "on", "yirmi", "otuz", "kırk",
    "elli", "altmış", "yetmiş", "seksen", "doksan", "yüz", "bin", "milyon", "milyar", "trilyon",
    "açık", "kapalı", "kötü", "iyi", "güzel", "çirkin", "sevimli", "korkutucu", "şirin", "yaramaz",
    "ciddi", "eğlenceli", "zor", "kolay", "yüksek", "alçak", "geniş", "dar", "sert", "yumuşak",
    "ahşap", "metal", "plastik", "cam", "kâğıt", "kalem", "silgi", "defter", "kitap", "harita",
    "şemsiye", "çanta", "ayakkabı", "giysi", "elbise", "tişört", "pantolon", "şort", "etek", "kravat",
    "takım", "saç", "göz", "kulak", "burun", "ağız", "diş", "dudak", "kaş", "yanak",
    "çene", "omuz", "kol", "el", "bacak", "ayak", "diz", "dirsek", "baş", "sırt",
    "karn", "kafa", "göğüs", "bel", "parmak", "tırnak", "döner", "süre", "zaman", "şimdi",
    "yarın", "dün", "gece", "gündüz", "sabah", "akşam", "yıl", "ay", "hafta", "gün",
    "saat", "dakika", "saniye", "an", "konu", "durum", "sebep", "sonuç", "kural", "olarak",
    "şey", "yöntem", "yazılım", "program", "bilgi", "veri", "hata", "geliştirme", "sistem", "hizmet",
    "sağlık", "şirket", "teknoloji", "eğitim", "hayat", "toplum", "dünya", "evren", "insanlık", "doğa","sandalye", "sofra", "çorba", "pizza", "hamburger", "tost", "salata", "şarkı", "müzik", "film",
    "televizyon", "bilgisayar", "telefon", "internet", "fotoğraf", "yazılım", "kütüphane", "oyun", "eğlence", "tarih",
    "coğrafya", "matematik", "fen", "kimya", "biyoloji", "fizik", "edebiyat", "resim", "mimarlık", "mühendislik",
    "tıp", "okuma", "yazma", "dinleme", "konuşma", "öğrenme", "anlama", "yazı", "kalem", "defter",
    "not", "soru", "cevap", "ödev", "sınıf", "ders", "öğrenci", "öğretmen", "sınav", "puan",
    "başarı", "hayal", "gerçek", "gül", "mutlu", "üzgün", "sevgi", "aşk", "nefret", "korku",
    "cesaret", "umut", "hayal", "mücadele", "özlem", "güç", "yetenek", "hobi", "spor", "sağlık",
    "beslenme", "uyku", "dinlenme", "yürüyüş", "koşu", "yüzme", "basketbol", "futbol", "tenis", "voleybol",
    "masa tenisi", "bisiklet", "kış", "yaz", "sonbahar", "ilkbahar", "mevsim", "hava durumu", "yağmur", "kar",
    "güneş", "bulut", "rüzgar", "fırtına", "sıcak", "soğuk", "sıcaklık", "soğukluk", "deniz", "okyanus",
    "dağ", "tepe", "vadi", "orman", "çöl", "nehir", "göl", "su", "toprak", "kaya",
    "kum", "bitki", "ağaç", "çalı", "çiçek", "meyve", "sebze", "tahıl", "hayvan", "kuş"
]